---
title: "Etude de cas : Explication des crimes à Boston et ses envrions"
author: "Nicolas Derumigny et Anton Daumen"
date: "6 Novembre 2017"
output: html_document
---
```{r setup, include=FALSE}
library(MASS)
library(ggplot2)
# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

## Premier affichage des données sélectionnées

```{r, fig.align="center"}
plt_nox <- ggplot(data=Boston, aes(x=nox, y=crim))  + geom_point()
plt_pupil <- ggplot(data=Boston, aes(x=ptratio, y=crim))  + geom_point()
plt_lstat <- ggplot(data=Boston, aes(x=lstat, y=crim))  + geom_point()
plt_age <- ggplot(data=Boston, aes(x=age, y=crim))  + geom_point()

multiplot(plt_nox, plt_pupil, plt_lstat, plt_age, cols=2)
```

## Regression lineaire Univarié

```{r, fig.align='center'}
plt_nox_1 <- ggplot(data=Boston, aes(x=nox, y=crim))  +
  geom_point(color='blue') +
  geom_smooth(method = "lm", color='red')

plt_pupil_1 <- ggplot(data=Boston, aes(x=ptratio, y=crim))  +
  geom_point(color='blue') +
  geom_smooth(method = "lm", color='red')

plt_poor_1 <- ggplot(data=Boston, aes(x=lstat, y=crim))  +
  geom_point(color='blue') +
  geom_smooth(method = "lm", color='red')

plt_age_1 <- ggplot(data=Boston, aes(x=age, y=crim))  +
  geom_point(color='blue') +
  geom_smooth(method = "lm", color='red')

multiplot(plt_nox, plt_pupil, plt_poor, plt_age, cols=2)
```


## Regression Linéaire Multivariée
```{r, include=FALSE}
ggplotRegression <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red") +
  labs(title = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                     "Intercept =",signif(fit$coef[[1]],5 ),
                     " Slope =",signif(fit$coef[[2]], 5),
                     " P =",signif(summary(fit)$coef[2,4], 5)))
}
```

```{r, fig.align="center"}
first_model <- lm(crim ~ nox + ptratio + lstat + age, data=Boston)

predicted <- data.frame(crime_nox = predict(first_model, Boston), nox=Boston$nox, ptratio=Boston$ptratio, lstat=Boston$lstat, age = Boston$age)

plt_nox <- ggplot(data=Boston, aes(x=nox, y=crim)) + geom_point(color="blue") + geom_line(color="red", data = predicted, aes(y=crime_nox, x=nox))
plt_pupil <- ggplot(data=Boston, aes(x=ptratio, y=crim))  + geom_point(color="blue") + geom_line(color="red", data = predicted, aes(y=crime_nox, x=ptratio))
plt_lstat <- ggplot(data=Boston, aes(x=lstat, y=crim))  + geom_point(color="blue") + geom_line(color="red", data = predicted, aes(y=crime_nox, x=lstat))
plt_age <- ggplot(data=Boston, aes(x=age, y=crim))  + geom_point(color="blue")+ geom_line(color="red", data = predicted, aes(y=crime_nox, x=age))
multiplot(plt_nox, plt_pupil, plt_lstat, plt_age, cols=2)
```

## Regression Polynomiale Multivariée
```{r, fig.align="center"}
snd_model <- lm(crim ~ nox + I(nox^2) + ptratio + I(ptratio^2) + lstat + I(lstat^2) + age + I(age^2), data=Boston)

predicted <- data.frame(crime_nox = predict(snd_model, Boston), nox=Boston$nox, ptratio=Boston$ptratio, lstat=Boston$lstat, age = Boston$age)

plt_nox <- ggplot(data=Boston, aes(x=nox, y=crim)) + geom_point(color="blue") + geom_line(color="red", data = predicted, aes(y=crime_nox, x=nox))
plt_pupil <- ggplot(data=Boston, aes(x=ptratio, y=crim))  + geom_point(color="blue") + geom_line(color="red", data = predicted, aes(y=crime_nox, x=ptratio))
plt_lstat <- ggplot(data=Boston, aes(x=lstat, y=crim))  + geom_point(color="blue") + geom_line(color="red", data = predicted, aes(y=crime_nox, x=lstat))
plt_age <- ggplot(data=Boston, aes(x=age, y=crim))  + geom_point(color="blue")+ geom_line(color="red", data = predicted, aes(y=crime_nox, x=age))
multiplot(plt_nox, plt_pupil, plt_lstat, plt_age, cols=2)
```